// import { v4 as uuidv4 } from "uuid";
const cat = {
  inverters: "inverters",
  batteries: "batteries",
  panels: "panels",
  appliances: "appliances",
  accessories: "accessories",
};
export const categories = [
  {
    _id: 1001,
    name: "Inverters",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=400&q=80",
    description: "High-efficiency solar inverters for residential and commercial use.",
    _base: "inverters",
  },
  {
    _id: 1002,
    name: "Batteries",
    image: "https://images.unsplash.com/photo-1464983953574-0892a716854b?auto=format&fit=crop&w=400&q=80",
    description: "Reliable energy storage solutions including lithium and lead-acid batteries.",
    _base: "batteries",
  },
  {
    _id: 1003,
    name: "Panels",
    image: "https://images.unsplash.com/photo-1509395176047-4a66953fd231?auto=format&fit=crop&w=400&q=80",
    description: "Premium solar panels for maximum energy generation.",
    _base: "panels",
  },
  {
    _id: 1004,
    name: "Appliances",
    image: "https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=400&q=80",
    description: "Energy-efficient appliances compatible with solar setups.",
    _base: "appliances",
  },
  {
    _id: 1005,
    name: "Accessories",
    image: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=400&q=80",
    description: "Cables, connectors, charge controllers, and more.",
    _base: "accessories",
  },
];

export const highlightsProducts = [
  {
    _id: 3001,
    name: "Solar Power Solutions",
    title: "Empowering Pakistan with Clean Energy",
    buttonTitle: "Shop Solar Panels",
    image: "https://images.unsplash.com/photo-1509395176047-4a66953fd231?auto=format&fit=crop&w=600&q=80",
    _base: "/category/panels",
    color: "#00796b",
  },
  {
    _id: 3002,
    name: "Reliable Backup Power",
    title: "Top Inverters & Batteries",
    buttonTitle: "Explore Inverters",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80",
    _base: "/category/inverters",
    color: "#388e3c",
  },
  {
    _id: 3003,
    name: "Solar Accessories",
    title: "Everything You Need for Installation",
    buttonTitle: "Browse Accessories",
    image: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=600&q=80",
    _base: "/category/accessories",
    color: "#fbc02d",
  },
];

export const blogsData = [
  {
    _id: 4001,
    image: "https://images.unsplash.com/photo-1464983953574-0892a716854b?auto=format&fit=crop&w=600&q=80",
    title: "Why Solar Energy is the Future of Pakistan",
    _base: "Renewable Energy",
    description:
      "Discover how solar energy is transforming the energy landscape in Pakistan, reducing costs and environmental impact.",
  },
  {
    _id: 4002,
    image: "https://images.unsplash.com/photo-1509395176047-4a66953fd231?auto=format&fit=crop&w=600&q=80",
    title: "Choosing the Right Inverter for Your Home",
    _base: "Solar Tips",
    description:
      "A guide to selecting the best inverter for your solar setup, including key features and top brands available in Pakistan.",
  },
  {
    _id: 4003,
    image: "https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=600&q=80",
    title: "Maximizing Battery Life in Solar Systems",
    _base: "Energy Storage",
    description:
      "Tips and tricks to extend the lifespan of your solar batteries and ensure reliable backup power.",
  },
];

export const products = [
  // Inverters
  {
    _id: 2001,
    name: "Growatt 5kW Hybrid Inverter",
    images: [
      "https://www.ginverter.com/uploads/2021/11/5kw-hybrid-inverter.jpg"
    ],
    description: "High-efficiency hybrid inverter for residential solar systems. WiFi monitoring included.",
    regularPrice: 180000,
    discountedPrice: 170000,
    quantity: 10,
    rating: 4.8,
    reviews: 34,
    category: "Inverters",
    brand: "Growatt",
    isStock: true,
    overView: "Hybrid Inverter",
    isNew: true,
    _base: cat.inverters,
    wattage: 5000,
    inverterType: "Hybrid",
    phaseType: "Single",
    warranty: "5 years",
    installationAvailable: true,
  },
  {
    _id: 2002,
    name: "Inverex Nitrox 3.2kW Solar Inverter",
    images: [
      "https://inverex.com.pk/wp-content/uploads/2022/03/nitrox-3.2kw.jpg"
    ],
    description: "Pure sine wave inverter with advanced MPPT technology for maximum efficiency.",
    regularPrice: 95000,
    discountedPrice: 90000,
    quantity: 15,
    rating: 4.6,
    reviews: 21,
    category: "Inverters",
    brand: "Inverex",
    isStock: true,
    overView: "Solar Inverter",
    isNew: false,
    _base: cat.inverters,
    wattage: 3200,
    inverterType: "Solar",
    phaseType: "Single",
    warranty: "3 years",
    installationAvailable: true,
  },
  // Batteries
  {
    _id: 2101,
    name: "Narada 12V 200Ah Gel Battery",
    images: [
      "https://www.naradapower.com/uploads/2020/12/12v-200ah-gel-battery.jpg"
    ],
    description: "Deep cycle gel battery for solar energy storage. Maintenance-free and long life.",
    regularPrice: 65000,
    discountedPrice: 63000,
    quantity: 20,
    rating: 4.7,
    reviews: 18,
    category: "Batteries",
    brand: "Narada",
    isStock: true,
    overView: "Solar Battery",
    isNew: true,
    _base: cat.batteries,
    warranty: "2 years",
    installationAvailable: false,
  },
  {
    _id: 2102,
    name: "Phoenix TX 2000 Tubular Battery",
    images: [
      "https://www.phoenixbattery.com.pk/wp-content/uploads/2021/05/tx-2000.jpg"
    ],
    description: "Tubular battery designed for deep discharge and long backup in solar systems.",
    regularPrice: 54000,
    discountedPrice: 52000,
    quantity: 25,
    rating: 4.5,
    reviews: 12,
    category: "Batteries",
    brand: "Phoenix",
    isStock: true,
    overView: "Tubular Battery",
    isNew: false,
    _base: cat.batteries,
    warranty: "2 years",
    installationAvailable: false,
  },
  // Panels
  {
    _id: 2201,
    name: "JA Solar 550W Mono PERC Panel",
    images: [
      "https://www.jasolar.com/uploadfile/2021/0812/20210812035718136.jpg"
    ],
    description: "High-efficiency monocrystalline solar panel for residential and commercial installations.",
    regularPrice: 42000,
    discountedPrice: 40000,
    quantity: 50,
    rating: 4.9,
    reviews: 40,
    category: "Panels",
    brand: "JA Solar",
    isStock: true,
    overView: "Mono PERC Panel",
    isNew: true,
    _base: cat.panels,
    wattage: 550,
    panelType: "Mono PERC",
    efficiency: 21.3,
    warranty: "12 years",
    installationAvailable: true,
  },
  {
    _id: 2202,
    name: "Canadian Solar 545W Panel",
    images: [
      "https://www.canadiansolar.com/sites/default/files/2021-03/CS3W-545MS.jpg"
    ],
    description: "Durable and efficient solar panel with high power output and performance warranty.",
    regularPrice: 43000,
    discountedPrice: 41000,
    quantity: 40,
    rating: 4.8,
    reviews: 28,
    category: "Panels",
    brand: "Canadian Solar",
    isStock: true,
    overView: "Solar Panel",
    isNew: false,
    _base: cat.panels,
    wattage: 545,
    panelType: "Mono",
    efficiency: 20.8,
    warranty: "12 years",
    installationAvailable: true,
  },
  // Appliances
  {
    _id: 2301,
    name: "DC Solar Fan 16-inch",
    images: [
      "https://5.imimg.com/data5/SELLER/Default/2022/7/ZW/GL/GL/1517266/solar-dc-fan-16-inch-500x500.jpg"
    ],
    description: "Energy-efficient DC fan compatible with solar systems. 3 speed settings.",
    regularPrice: 8500,
    discountedPrice: 8000,
    quantity: 30,
    rating: 4.4,
    reviews: 10,
    category: "Appliances",
    brand: "Generic",
    isStock: true,
    overView: "Solar Fan",
    isNew: true,
    _base: cat.appliances,
    warranty: "1 year",
    installationAvailable: false,
  },
  {
    _id: 2302,
    name: "DC LED Bulb 12W",
    images: [
      "https://www.solarshop.pk/wp-content/uploads/2020/09/dc-led-bulb-12w.jpg"
    ],
    description: "Bright and efficient 12W DC LED bulb for solar and backup systems.",
    regularPrice: 350,
    discountedPrice: 320,
    quantity: 100,
    rating: 4.6,
    reviews: 22,
    category: "Appliances",
    brand: "Generic",
    isStock: true,
    overView: "LED Bulb",
    isNew: false,
    _base: cat.appliances,
    warranty: "6 months",
    installationAvailable: false,
  },
  // Accessories
  {
    _id: 2401,
    name: "MC4 Solar Connector Pair",
    images: [
      "https://www.solarshop.pk/wp-content/uploads/2020/09/mc4-connector-pair.jpg"
    ],
    description: "Standard MC4 connectors for safe and secure solar panel connections.",
    regularPrice: 400,
    discountedPrice: 350,
    quantity: 200,
    rating: 4.7,
    reviews: 15,
    category: "Accessories",
    brand: "Generic",
    isStock: true,
    overView: "Solar Connector",
    isNew: true,
    _base: cat.accessories,
    warranty: "6 months",
    installationAvailable: false,
  },
  {
    _id: 2402,
    name: "30A MPPT Solar Charge Controller",
    images: [
      "https://www.solarshop.pk/wp-content/uploads/2020/09/30a-mppt-charge-controller.jpg"
    ],
    description: "Efficient MPPT charge controller for optimal battery charging from solar panels.",
    regularPrice: 7500,
    discountedPrice: 7000,
    quantity: 35,
    rating: 4.5,
    reviews: 8,
    category: "Accessories",
    brand: "Generic",
    isStock: true,
    overView: "Charge Controller",
    isNew: false,
    _base: cat.accessories,
    warranty: "1 year",
    installationAvailable: false,
  },
];
